### ISSUE TITLE
feat: Automatic Gain Control

### ISSUE THREAD

**Issue by CillianMyles** [alnitak/flutter_recorder#7]
**Description**

Each OS has some kind of automatic control to keep microphone stream data virtually consistent across devices, OS versions, etc. for voice applications

It would be nice if we could have automatic gain control as part of this plugin. 

**Requirements**

- [ ] Automatic Gain Control option to keep audio stream data virtually consistent

**Additional Context**

Android's native option: https://developer.android.com/reference/android/media/audiofx/AutomaticGainControl

**Comment by alnitak** [comment]
Thank you @CillianMyles,

I will consider this like the echo cancellation filter #5 

I will update these issues with news if any.

**Comment by alnitak** [comment]
Hi @alnitak,

I made a new branch named `autogain` and it is discussed in PR #12 

If you are in the mood to try it, I am eager to hear from you! Seems to work as expected but I have not the knowledge to test it.

**Comment by CillianMyles** [comment]
Awesome. Thank you @alnitak 🙏 

I will test this, and get back to you properly about #8, as soon as I can!

**Comment by CillianMyles** [comment]
For macOS and iOS I am getting compilation errors, and for Android the echo/background noise I described in #8 makes it very hard to test the difference.

In the meantime here are the compilation errors...

macOS:
```
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/macos/Classes/../../src/filters/autogain.cpp:103:23: error: no member named 'clamp' in namespace 'std'
    targetGain = std::clamp(targetGain, getParamValue(MinGain), getParamValue(MaxGain));
                 ~~~~~^
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/macos/Classes/../../src/filters/autogain.cpp:199:27: error: no member named 'clamp' in namespace 'std'
            sample = std::clamp(sample, -1.0f, 1.0f);
                     ~~~~~^
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/macos/Classes/../../src/filters/autogain.cpp:207:27: error: no member named 'clamp' in namespace 'std'
            sample = std::clamp(sample, -1.0f, 1.0f);
                     ~~~~~^
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/macos/Classes/../../src/filters/autogain.cpp:222:37: error: no member named 'clamp' in namespace 'std'
            normalizedSample = std::clamp(normalizedSample, -1.0f, 1.0f);
                               ~~~~~^
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/macos/Classes/../../src/filters/autogain.cpp:226:36: error: no member named 'clamp' in namespace 'std'
            processedSample = std::clamp(processedSample, -8388608, 8388607);
                              ~~~~~^
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/macos/Classes/../../src/filters/autogain.cpp:238:27: error: no member named 'clamp' in namespace 'std'
            sample = std::clamp(sample, -1.0f, 1.0f);
                     ~~~~~^
6 errors generated.
```

iOS:
```
Semantic Issue (Xcode): No member named 'clamp' in namespace 'std'
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/src/filters/autogain.cpp:102:22

Semantic Issue (Xcode): No member named 'clamp' in namespace 'std'
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/src/filters/autogain.cpp:198:26

Semantic Issue (Xcode): No member named 'clamp' in namespace 'std'
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/src/filters/autogain.cpp:206:26

Semantic Issue (Xcode): No member named 'clamp' in namespace 'std'
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/src/filters/autogain.cpp:221:36

Semantic Issue (Xcode): No member named 'clamp' in namespace 'std'
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/src/filters/autogain.cpp:225:35

Semantic Issue (Xcode): No member named 'clamp' in namespace 'std'
/Users/cillian/.pub-cache/git/flutter_recorder-d3107e0125ac56ee18c0b79c0fb1368475cd9f31/src/filters/autogain.cpp:237:26

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15.
```

---

```yml
  # Automatic Gain Control
  flutter_recorder:
    git:
      url: https://github.com/alnitak/flutter_recorder.git
      ref: d3107e0125ac56ee18c0b79c0fb1368475cd9f31
```

---

macOS: Sonoma 14.4.1 (23E224)
Flutter: 3.27.0-1.0.pre.554
Dart: 3.7.0

**Comment by CillianMyles** [comment]
Apologies for the delay here, I am working on other things in parallel.

Some good news... 🎉 

I discovered that the artefacts were happening when I was buffering the audio bytes every 100ms before sending to the server. Removing this buffering completely fixed that issue. 

Weird that this buffering caused the artefacts for this plugin and not `record`, maybe some async issue on my end. 

I do need to figure out a way to successfully do the buffering or I'll be flooding the server, but now it is no longer the most immediate issue.

Before I can get this into an internal test build of my app, which is the only reasonable way for me to test the gain on a number of devices where I've previously had issues, I have a couple things to resolve:

1. there are compilation errors on web:

```
Waiting for connection from debug service on Chrome...
../../../../../../.pub-cache/git/flutter_recorder-a1c8a1a639c043176a2dd7bf96852526dfc678ee/lib/src/bindings/recorder_web.dart:30:7: Error: The non-abstract class 'RecorderWeb' is missing implementations for these members:
 - RecorderImpl.addFilter
 - RecorderImpl.getFilterParamNames
 - RecorderImpl.getFilterParamValue
 - RecorderImpl.isFilterActive
 - RecorderImpl.removeFilter
 - RecorderImpl.setFilterParamValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RecorderWeb extends RecorderImpl {
      ^^^^^^^^^^^
../../../../../../.pub-cache/git/flutter_recorder-a1c8a1a639c043176a2dd7bf96852526dfc678ee/lib/src/bindings/recorder.dart:225:8: Context: 'RecorderImpl.addFilter' is defined here.
  void addFilter(FilterType filterType);
       ^^^^^^^^^
../../../../../../.pub-cache/git/flutter_recorder-a1c8a1a639c043176a2dd7bf96852526dfc678ee/lib/src/bindings/recorder.dart:236:16: Context: 'RecorderImpl.getFilterParamNames' is defined here.
  List<String> getFilterParamNames(FilterType filterType);
               ^^^^^^^^^^^^^^^^^^^
../../../../../../.pub-cache/git/flutter_recorder-a1c8a1a639c043176a2dd7bf96852526dfc678ee/lib/src/bindings/recorder.dart:248:10: Context: 'RecorderImpl.getFilterParamValue' is defined here.
  double getFilterParamValue(FilterType filterType, int attributeId);
         ^^^^^^^^^^^^^^^^^^^
../../../../../../.pub-cache/git/flutter_recorder-a1c8a1a639c043176a2dd7bf96852526dfc678ee/lib/src/bindings/recorder.dart:217:7: Context: 'RecorderImpl.isFilterActive' is defined here.
  int isFilterActive(FilterType filterType);
      ^^^^^^^^^^^^^^
../../../../../../.pub-cache/git/flutter_recorder-a1c8a1a639c043176a2dd7bf96852526dfc678ee/lib/src/bindings/recorder.dart:232:17: Context: 'RecorderImpl.removeFilter' is defined here.
  CaptureErrors removeFilter(FilterType filterType);
                ^^^^^^^^^^^^
../../../../../../.pub-cache/git/flutter_recorder-a1c8a1a639c043176a2dd7bf96852526dfc678ee/lib/src/bindings/recorder.dart:240:8: Context: 'RecorderImpl.setFilterParamValue' is defined here.
  void setFilterParamValue(
       ^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```

2. not necessarily a test build blocker, but blocks me getting this into the app - hot restart throws:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: RecorderInitializeFailedException: An error occurred while initializing recorder. Maybe it is already inited? (on the C++ side).
#0      RecorderFfi.init (package:flutter_recorder/src/bindings/recorder_io.dart:194:7)
#1      Recorder.init (package:flutter_recorder/src/flutter_recorder.dart:159:21)
#2      _PageState._initRecorders (package:flutter_recorder_agc/main.dart:68:9)
#3      _PageState._requestPermission.<anonymous closure> (package:flutter_recorder_agc/main.dart:57:13)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:932:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:961:13)
#6      Future._completeWithValue (dart:async/future_impl.dart:712:5)
<asynchronous suspension>
```

**Comment by CillianMyles** [comment]
Awesome thank you @alnitak - I'll:

1. put a platform stub in place to use `record` for web for the time being to test AGC on Android
2. check if the recorder is initialized! Although I wonder is there any point exposing that detail to the plugin consumer - you could do the check yourself internally? Just an idea. Maybe there is a reason you want to expose it :-)

**Comment by alnitak** [comment]
1. I think a stub is not necessary if you compile on other platforms than the web, I mean you should not get compile errors on Android.
2. I should think about that. Also in *flutter_soloud* we did the same, I will propose it.

**Comment by CillianMyles** [comment]
@alnitak reason I am going want to shim web is because I want to merge this to a branch from which all internal builds are compiled from, so that I can test it on a number of devices over a few of days.

**Comment by alnitak** [comment]
Hey @CillianMyles , web is now supported in #12.

Now it is working together `flutter_soloud` and in the `loopback.dart` example you can test autoGain filter listening, almost in real time, how the input audio is filtered! (use a headset to prevent audio feedback).

I am closing this and leaving the PR in a draft state, so if there are some problems we can discuss them there.
